- name: Disbale redis default
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis 7
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install Redis 7
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Update Redis Config - Update Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis Config Gile - Update Protect Mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes



#PRINT Disbale redis default
#dnf module disable redis -y &>>$LOG_FILE
#STAT $?
#
#PRINT Enable redis 7
#dnf module enable redis:7 -y &>>$LOG_FILE
#STAT $?

#PRINT Install Redis 7
#dnf install redis -y &>>$LOG_FILE
#STAT $?

#PRINT Update Redis Config
#sed -i -e '/^bind/ s/127.0.0.1/0.0.0.0/' -e '/protected-mode/ c protected-mode no' /etc/redis/redis.conf &>>$LOG_FILE
#STAT $?

#PRINT Start Redis Service
#systemctl enable redis &>>$LOG_FILE
#systemctl restart redis &>>$LOG_FILE
#STAT $?