- name: Disable Nginx default Version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    name: nginx
    state: restart
    enabled: true




#PRINT Disable Nginx default Version
#dnf module disable nginx -y  &>>$LOG_FILE
#STAT $?
#
#PRINT Enable Nginx 24 Version
# &>>$LOG_FILE
#STAT $?

#PRINT Install Nginx
#dnf install nginx -y  &>>$LOG_FILE
#STAT $?

#PRINT Copy nginx config file
#cp nginx.conf /etc/nginx/nginx.conf  &>>$LOG_FILE
#STAT $?

APP_PREREQ

#PRINT Start Nginx Service
#systemctl enable nginx  &>>$LOG_FILE
#systemctl restart nginx  &>>$LOG_FILE
#STAT $?
