- name: Install Maven and Java
  ansible.builtin.dnf:
    name: maven

- name: Setup APP Prerequisites
  ansible.builtin.include_role:
    name: common
    task_from: app_prereq

- name: Download Dependencies
  ansible.builtin.shell: mvn clean package ;mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: "{{ app_path }}"


- name: SCHEMA_SETUP
  ansible.builtin.include_role:
    name: common
    task_from: schema
  when: schema_setup is defined

- name: SYSTEMD_SETUP
  ansible.builtin.include_role:
    name: common
    task_from: systemd




#PRINT Install Maven and Java
#dnf install maven -y &>>$LOG_FILE
#STAT $?

#APP_PREREQ

#PRINT Download Dependencies
#mvn clean package &>>$LOG_FILE
#mv target/shipping-1.0.jar shipping.jar &>>$LOG_FILE
#STAT $?

#SCHEMA_SETUP
#SYSTEMD_SETUP